### PR TITLE
Update to LESS 2.4

### PR DESCRIPTION
**Pull request by jessegrosjean**
This updates to LESS 2.4. The less-cache specs all pass.

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Sorry for the longer delay in reviewing and merging this, what do you think about going to less 2.5 in this PR?

**Comment by jessegrosjean** [comment]
Just updated to LESS ^2.5.0

**Comment by silvestreh** [comment]
Sorry to bug, but … any updates on this? I could very much benefit from an updated LESS in my theme :smile:

**Comment by thomasjo** [comment]
This was superseded by #10. Sorry about not spotting this earlier!

---
@lee-dohm, @maxbrunsfeld, @nathansobo: This can be closed.

**Comment by silvestreh** [comment]
@thomasjo so looks like Atom ships with Less 2.7.1. It's strange because I still can't use [optional imports](http://lesscss.org/features/#import-options). What would be the best repo to open an issue for this?

**Comment by mthadley** [comment]
@silvestreh I just ran into the same issue and was wondering the same thing. Looks like these changes in this package are in `0.24`, however atom core is still using [`0.23`](https://github.com/atom/atom/blob/master/package.json#L40). But hopefully that will be bumped soon.

**Comment by thomasjo** [comment]
If you read [earlier comments](https://github.com/atom/less-cache/pull/10) in this thread, you'll see that it has already been bumped. It will land in a future release of Atom after atom/atom#12300 ships.

**Comment by mthadley** [comment]
Awesome! Looking forward to it! Just to clarify I was referring to the version of `less-cache` in atom which has not been bumped yet.

**Pull request closed without merging**
